repos:
  # for code in .md files
  # (patched with support for codeblock options and `py` shortcodes)
  - repo: https://github.com/shiftinv/blacken-docs
    rev: 161c8eff80b7e1dc388151974aa5ab9010741e09
    hooks:
    - id: blacken-docs
      additional_dependencies: [black==21.9b0]
      args: [--line-length=100]
  # for code samples
  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
    - id: black
      args: [--line-length=100]
  # for markdown formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
    - id: prettier
      types_or: [html, css, javascript, markdown]
      args: [--print-width=120, --tab-width=4, --prose-wrap=always]
