site_name: Disnake Guide
site_description: A guide for disnake.
site_url: https://guide.disnake.dev/

theme:
    name: material
    logo: disnake.png
    favicon: disnake.png
    features:
        - navigation.sections
        - navigation.instant
        - navigation.top
        - navigation.tracking
        - toc.integrate
    language: en
    palette:
        - media: "(prefers-color-scheme: light)"
          scheme: light
          toggle: 
            icon: material/weather-sunny
            name: Light Mode
        - media: "(prefers-color-scheme: dark)"
          scheme: dark
          toggle:
            icon: material/weather-night
            name: Dark Mode

repo_name: DisnakeDev/disnake
repo_url: https://github.com/DisnakeDev/disnake
edit_uri: ""

plugins:
    - search
    - macros
    - git-revision-date-localized:
        type: date

extra: {
    disnakedocs: https://disnake.readthedocs.io/en/latest,
    dpydocs: https://discordpy.readthedocs.io/en/latest,
    discord: https://www.discord.com,
    discordsupport: https://support.discord.com/hc/en-us
}

markdown_extensions:
    - tables
    - admonition
    - attr_list
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.superfences
    - pymdownx.snippets
    - pymdownx.details
    - pymdownx.superfences
    - markdown_link_attr_modifier:
        new_tab: external_only
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - toc:
        permalink: True

nav:
    - index.md
    - links-credits.md
    - Prerequisites:
        - 000-prerequisites/001-installing-python.md
    - Getting Started:
        - 100-getting-started/101-making-your-application.md
        - 100-getting-started/102-coding-your-bot.md
    - Command Samples:
        - commands/index.md
        - commands/basic.md
    - good-practices/index.md

extra_css:
    - stylesheets/lightmode.css
    - stylesheets/darkmode.css
