name: Page/Section Addition
description: Suggestion for a new page/section that doesn't already exist.
labels: ["t: page/section addition"]
body:
  - type: markdown
    attributes:
      value: >
        Thanks for taking the time to open an issue! We advise you to make the report descriptive of the issue, with links and images wherever required. 
        Also make sure to go through the [`Contributing Guidelines`](https://github.com/DisnakeDev/guide/blob/main/CONTRIBUTING.md)!
  - type: input
    attributes:
      label: Expands on
      description: >
        Does this page/section expand on something else?
        If so, please provide a link to the page/section.
      placeholder: guide.disnake.dev/intents
  - type: input
    attributes:
      label: "Title"
      description: "Short, one-line summary of the addition"
      placeholder: "How to use Gateway Intents"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Description"
      description: "A few sentences of what this would teach. If you have screenshots, examples, or links, add them here."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Context
      description: If there is anything else to say, please do so here.
  - type: dropdown
    attributes:
      label: Would you like to implement this yourself?
      multiple: false
      options:
        - Yes, I'd like to write this
        - No, someone else can write it!
    validations:
      required: true
